"""Auth contract tests — auto-generated by AuthAgent.

DO NOT EDIT: this file is regenerated each AuthAgent run from
AUTH_CONTRACT.md. Manual edits will be overwritten.

Asserts the runtime auth contract holds against the live FusionAuth
stack: JWKS reachable, every contract test user can log in, and each
JWT decodes with the expected issuer + roles.

Runs in the integration phase (pytest sidecar joined to the compose
network — ``http://auth:9011`` resolves).
"""
import os
import json
import base64
from typing import Tuple

import httpx
import pytest


_FA_URL = (
    os.environ.get("FUSIONAUTH_URL")
    or os.environ.get("FUSIONAUTH_HOST_URL")
    or "http://auth:9011"
)
_APP_ID = "85a03867-dccf-4882-adde-1a79aeec50df"
_ISSUER = "acme.com"


def _decode_jwt_payload(token: str) -> dict:
    """Decode a JWT's payload without verifying the signature.

    Used here only to inspect claims; the SERVER-side code does
    proper RS256 verification via the JWKS document.
    """
    parts = token.split(".")
    if len(parts) != 3:
        raise ValueError(f"malformed JWT: {len(parts)} parts")
    payload_b64 = parts[1]
    # base64 with stripped padding — pad to multiple of 4.
    padded = payload_b64 + "=" * (-len(payload_b64) % 4)
    return json.loads(base64.urlsafe_b64decode(padded))


def _login(email: str, password: str) -> Tuple[int, dict]:
    r = httpx.post(
        f"{_FA_URL}/api/login",
        json={
            "applicationId": _APP_ID,
            "loginId": email,
            "password": password,
        },
        timeout=15,
    )
    try:
        body = r.json()
    except Exception:
        body = {"raw": r.text}
    return r.status_code, body

def test_jwks_reachable_and_rs_signed():
    """JWKS endpoint must be reachable and contain at least one RS-
    family key. Without this, the backend's ``algorithms=['RS256']``
    JWT verification has no key to verify with."""
    r = httpx.get(f"{_FA_URL}/.well-known/jwks.json", timeout=10)
    assert r.status_code == 200, (
        f"JWKS endpoint returned {r.status_code}: {r.text[:200]}"
    )
    keys = r.json().get("keys", [])
    assert keys, "JWKS document has zero keys"
    rs_keys = [k for k in keys if (k.get("alg") or "").upper().startswith("RS")]
    assert rs_keys, (
        f"JWKS has {len(keys)} key(s) but none are RS-family: "
        f"{[k.get('alg') for k in keys]}"
    )


def test_user_login_user_example_com():
    """Test user `user@example.com` (roles: user) must log in
    cleanly and receive an RS256 JWT. Audit was green at AuthAgent
    submit time; this is the runtime regression guard."""
    status, body = _login("user@example.com", "password")
    assert status == 200, (
        f"login for user@example.com returned {status}: {body}"
    )
    token = body.get("token")
    assert token, f"login for user@example.com returned no token: {body}"
    payload = _decode_jwt_payload(token)
    iss = payload.get("iss") or ""
    assert iss == _ISSUER, (
        f"user iss claim mismatch: expected {_ISSUER!r}, got {iss!r}"
    )
    roles = payload.get("roles") or []
    expected = ['user']
    for role in expected:
        assert role in roles, (
            f"user user@example.com JWT missing expected role {role!r}; got {roles}"
        )


def test_user_login_admin_example_com():
    """Test user `admin@example.com` (roles: admin) must log in
    cleanly and receive an RS256 JWT. Audit was green at AuthAgent
    submit time; this is the runtime regression guard."""
    status, body = _login("admin@example.com", "password")
    assert status == 200, (
        f"login for admin@example.com returned {status}: {body}"
    )
    token = body.get("token")
    assert token, f"login for admin@example.com returned no token: {body}"
    payload = _decode_jwt_payload(token)
    iss = payload.get("iss") or ""
    assert iss == _ISSUER, (
        f"user iss claim mismatch: expected {_ISSUER!r}, got {iss!r}"
    )
    roles = payload.get("roles") or []
    expected = ['admin']
    for role in expected:
        assert role in roles, (
            f"user admin@example.com JWT missing expected role {role!r}; got {roles}"
        )
