# Backward-compatibility shim
from bizniz.agents.debugger.prompts.agentic_system_prompt import AGENTIC_DEBUGGER_SYSTEM_PROMPT
from bizniz.agents.debugger.prompts.agentic_schema import AgenticDebuggerActionSchema
