"""Unit tests for the User SQLAlchemy 2.0 model definition.

Tests inspect the declarative model metadata directly — no DB
connection required. CITEXT and PG_UUID are Postgres-specific
types and can't be materialised by SQLite, so we verify the
schema by introspecting ``__table__`` instead of running DDL.
"""
import uuid

import pytest
from sqlalchemy import CheckConstraint, DateTime, String
from sqlalchemy.dialects.postgresql import CITEXT
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.sql.functions import now as sql_now

from app.db.base import Base
from app.models.user import User


@pytest.mark.unit
class TestUserModelStructure:
    """Column-level metadata: name, type, nullability, defaults."""

    def test_tablename_is_users(self):
        assert User.__tablename__ == "users"

    def test_inherits_from_base(self):
        assert issubclass(User, Base)

    def test_registered_in_metadata(self):
        assert "users" in Base.metadata.tables

    def test_has_expected_columns(self):
        expected = {"id", "email", "role", "display_name", "created_at", "updated_at"}
        assert set(User.__table__.columns.keys()) == expected

    def test_id_is_primary_key_pg_uuid(self):
        col = User.__table__.c.id
        assert col.primary_key is True
        assert isinstance(col.type, PG_UUID)
        assert col.type.as_uuid is True
        # No autogenerated default — caller (auth mirror) supplies FA sub.
        assert col.default is None
        assert col.server_default is None

    def test_email_citext_254_unique_not_null(self):
        col = User.__table__.c.email
        assert isinstance(col.type, CITEXT)
        assert col.type.length == 254
        assert col.unique is True
        assert col.nullable is False

    def test_role_string_20_not_null_default_user(self):
        col = User.__table__.c.role
        assert isinstance(col.type, String)
        assert col.type.length == 20
        assert col.nullable is False
        assert col.server_default is not None
        assert col.server_default.arg == "user"

    def test_display_name_string_100_nullable(self):
        col = User.__table__.c.display_name
        assert isinstance(col.type, String)
        assert col.type.length == 100
        assert col.nullable is True

    def test_created_at_timestamptz_server_default_now_not_null(self):
        col = User.__table__.c.created_at
        assert isinstance(col.type, DateTime)
        assert col.type.timezone is True
        assert col.nullable is False
        assert col.server_default is not None
        assert isinstance(col.server_default.arg, sql_now)
        # created_at must NOT bump on UPDATE.
        assert col.onupdate is None

    def test_updated_at_timestamptz_server_default_and_onupdate_now(self):
        col = User.__table__.c.updated_at
        assert isinstance(col.type, DateTime)
        assert col.type.timezone is True
        assert col.nullable is False
        assert col.server_default is not None
        assert isinstance(col.server_default.arg, sql_now)
        assert col.onupdate is not None
        # onupdate is wrapped in a ColumnElementColumnDefault; the
        # underlying SQL function is what we care about.
        assert isinstance(col.onupdate.arg, sql_now)


@pytest.mark.unit
class TestUserRoleCheckConstraint:
    """The role column must be guarded by a CHECK constraint."""

    def _role_check(self) -> CheckConstraint:
        cks = [
            c
            for c in User.__table__.constraints
            if isinstance(c, CheckConstraint)
        ]
        assert cks, "User table has no CheckConstraint"
        # There should be exactly one CK we authored — the role guard.
        role_cks = [c for c in cks if "role" in str(c.sqltext).lower()]
        assert role_cks, f"No role CheckConstraint found among {cks}"
        return role_cks[0]

    def test_role_check_constraint_present_and_named(self):
        ck = self._role_check()
        # The metadata naming convention renders the final name as
        # ck_<table>_<short_name>; we expect 'ck_users_role'.
        assert ck.name == "ck_users_role"

    def test_role_check_constraint_lists_allowed_values(self):
        ck = self._role_check()
        sql = str(ck.sqltext)
        for role in ("'user'", "'admin'", "'super_admin'"):
            assert role in sql, f"Role {role} missing from CHECK clause: {sql}"


@pytest.mark.unit
class TestUserModelInstantiation:
    """The model must be instantiable with the documented kwargs."""

    def test_can_instantiate_with_minimum_fields(self):
        u = User(id=uuid.uuid4(), email="cook@example.com")
        assert u.email == "cook@example.com"
        assert u.display_name is None

    def test_can_instantiate_with_all_fields(self):
        uid = uuid.uuid4()
        u = User(
            id=uid,
            email="admin@example.com",
            role="admin",
            display_name="Site Admin",
        )
        assert u.id == uid
        assert u.role == "admin"
        assert u.display_name == "Site Admin"
