"""v5 canonical findings types.

A CanonicalFinding is one defect the reviewer flagged at iter 1 of
review/repair. It carries a stable ``id`` (the fingerprint) so the
ResolutionChecker can refer to specific findings across iters
without re-judging them. Status transitions are constrained:

  initial → still_present (after first iter that didn't resolve it)
  initial → resolved      (after first iter that fixed it)
  still_present → resolved
  resolved → regressed    (the danger case — was fixed, broke again)
  any → wont_fix          (operator escape; not currently auto-set
                           but reserved for future use)

The reviewer at iter 2+ ONLY sets these statuses on existing
findings. It cannot add new findings to the report — that's the
whole point of canonicalization.
"""
from __future__ import annotations

from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field


# ── Status + priority ─────────────────────────────────────────────


ResolutionStatus = Literal[
    "initial",          # iter 1: just created, no resolution check yet
    "still_present",    # resolution check: defect still in code
    "resolved",         # resolution check: defect no longer present
    "regressed",        # was resolved at iter N-1, broken again at iter N
    "wont_fix",         # operator escape — finding kept but doesn't block
]


FindingSource = Literal[
    "quality_engineer",     # QE.review missing scenarios + coverage gaps
    "code_reviewer",        # CR critical findings (flagged_symbols, etc.)
    "pytest",               # actual test failures (post-IMPLEMENT pytest)
    "static_symbol",        # symbol_validator (rare; usually advisory)
    "static_ast",           # AST syntax errors
]


FindingPriority = Literal[
    "critical",     # ship-blocker
    "important",    # should fix
    "nice_to_have", # may skip; doesn't block approval
]


# ── Canonical finding ─────────────────────────────────────────────


class CanonicalFinding(BaseModel):
    """One frozen defect from iter-1's full review.

    ``id`` is the fingerprint — stable across iters so the
    resolution check can refer to it by name. See ``fingerprint.py``.
    """

    id: str = Field(
        ...,
        description=(
            "Stable fingerprint. Format: `<source>:<capability_id?>:"
            "<short_hash>`. Generated by ``canonical_fingerprint()`` "
            "from the finding's source-specific shape."
        ),
    )
    source: FindingSource = Field(
        ..., description="Which reviewer/source produced this finding.",
    )
    priority: FindingPriority = Field(
        default="important",
        description=(
            "critical = blocks approval; important = blocks unless "
            "wont_fix; nice_to_have = doesn't block."
        ),
    )
    capability_id: Optional[str] = Field(
        default=None,
        description="EnrichedSpec capability id this finding relates to.",
    )
    summary: str = Field(
        ...,
        description="One-line human-readable description.",
    )
    file_hint: Optional[str] = Field(
        default=None,
        description=(
            "Workspace-relative file path the finding likely concerns. "
            "Used by the resolution check to know WHERE to look."
        ),
    )
    detail: str = Field(
        default="",
        description=(
            "Source-specific raw detail (e.g., the CR finding's "
            "evidence block, the QE missing-scenario text). The "
            "resolution checker uses this to decide if the defect is "
            "still present."
        ),
    )
    status: ResolutionStatus = Field(
        default="initial",
        description="Current resolution status.",
    )
    iter_resolved: Optional[int] = Field(
        default=None,
        description="If resolved/regressed, which iter index it happened.",
    )

    def is_blocker(self) -> bool:
        """True if this finding blocks milestone approval."""
        if self.status == "resolved":
            return False
        if self.status == "wont_fix":
            return False
        # initial / still_present / regressed all block by priority.
        return self.priority in ("critical", "important")


# ── Canonical report ──────────────────────────────────────────────


class CanonicalReport(BaseModel):
    """The frozen set of findings from iter 1 of review/repair.

    Set at iter 1; never re-judged. The reviewer at iter 2+ can ONLY
    update existing findings' statuses (via apply_resolution).
    """

    milestone_name: str = Field(..., description="Milestone this report is for.")
    iter_frozen: int = Field(
        default=1,
        description="Which review/repair iter froze this report (always 1).",
    )
    findings: List[CanonicalFinding] = Field(default_factory=list)

    # ── Queries ──────────────────────────────────────────────────

    def by_id(self) -> Dict[str, CanonicalFinding]:
        return {f.id: f for f in self.findings}

    def unresolved(self) -> List[CanonicalFinding]:
        """Findings that still need work (not resolved, not wont_fix)."""
        return [f for f in self.findings if f.status not in ("resolved", "wont_fix")]

    def blockers(self) -> List[CanonicalFinding]:
        return [f for f in self.findings if f.is_blocker()]

    def all_blockers_resolved(self) -> bool:
        return not self.blockers()

    def count_by_status(self) -> Dict[str, int]:
        out: Dict[str, int] = {}
        for f in self.findings:
            out[f.status] = out.get(f.status, 0) + 1
        return out

    def summary_line(self) -> str:
        c = self.count_by_status()
        return (
            f"canonical: {len(self.findings)} total "
            f"({c.get('resolved', 0)} resolved, "
            f"{c.get('still_present', 0) + c.get('initial', 0)} pending, "
            f"{c.get('regressed', 0)} regressed, "
            f"{c.get('wont_fix', 0)} wont_fix)"
        )

    # ── Mutations ────────────────────────────────────────────────

    def apply_resolution(
        self, resolution: "ResolutionReport", iter_idx: int,
    ) -> "ResolutionDelta":
        """Apply a resolution report's status updates to this canonical
        report. Returns a delta object summarizing what changed."""
        by_id = self.by_id()
        delta = ResolutionDelta(iter_idx=iter_idx)
        for r in resolution.resolutions:
            f = by_id.get(r.finding_id)
            if f is None:
                # Resolution check reported on a finding we don't have.
                # Skip — never invent.
                delta.unknown_ids.append(r.finding_id)
                continue
            prior = f.status
            new = r.status
            if prior == new:
                continue
            # Detect regression: prior was resolved, new is still/regressed.
            if prior == "resolved" and new in ("still_present", "regressed"):
                f.status = "regressed"
                f.iter_resolved = iter_idx
                delta.regressed_ids.append(f.id)
            elif new == "resolved":
                f.status = "resolved"
                f.iter_resolved = iter_idx
                delta.newly_resolved_ids.append(f.id)
            else:
                # initial → still_present, etc.
                f.status = new
                delta.status_changed_ids.append(f.id)
        return delta

    def find_findings_to_target(
        self, max_count: int = 10,
    ) -> List[CanonicalFinding]:
        """Pick which findings to target in the next repair iter.
        Blockers first, then ``initial``, then ``still_present``."""
        out: List[CanonicalFinding] = []
        # Critical regressions first.
        for f in self.findings:
            if f.is_blocker() and f.status == "regressed":
                out.append(f)
        # Then critical initials + still_present.
        for f in self.findings:
            if f in out:
                continue
            if f.is_blocker():
                out.append(f)
        return out[:max_count]


# ── Resolution check ──────────────────────────────────────────────


class FindingResolution(BaseModel):
    """One resolution-check verdict for a single canonical finding."""

    finding_id: str = Field(..., description="The CanonicalFinding.id.")
    status: ResolutionStatus = Field(
        ...,
        description=(
            "What the reviewer found this iter. Constrained to the "
            "resolution-check vocabulary: resolved / still_present / "
            "regressed."
        ),
    )
    evidence: str = Field(
        default="",
        description=(
            "One-line reason for the verdict — used for logs + future "
            "won't-fix decisions. Not authoritative."
        ),
    )


class ResolutionReport(BaseModel):
    """Output of one ResolutionChecker invocation. Constrained: only
    statuses for findings we already have. No new findings."""

    milestone_name: str
    iter_idx: int = Field(..., description="Which review/repair iter this is.")
    resolutions: List[FindingResolution] = Field(default_factory=list)

    def by_id(self) -> Dict[str, FindingResolution]:
        return {r.finding_id: r for r in self.resolutions}


# ── Delta (for the loop's progress accounting) ────────────────────


class ResolutionDelta(BaseModel):
    """Side-effect summary of ``apply_resolution`` — what changed in
    this iter. Used by the v5 loop to decide progress vs regression
    vs stall."""

    iter_idx: int
    newly_resolved_ids: List[str] = Field(default_factory=list)
    regressed_ids: List[str] = Field(default_factory=list)
    status_changed_ids: List[str] = Field(default_factory=list)
    unknown_ids: List[str] = Field(default_factory=list)

    @property
    def progress_count(self) -> int:
        """Net positive movement this iter."""
        return len(self.newly_resolved_ids)

    @property
    def regression_count(self) -> int:
        return len(self.regressed_ids)

    @property
    def is_progress(self) -> bool:
        return self.progress_count > 0 and self.regression_count == 0

    @property
    def is_regression(self) -> bool:
        return self.regression_count > 0
