"""Postgres infrastructure template."""
from __future__ import annotations

from bizniz.provisioner.templates.base import (
    InfraTemplate,
    TemplateContext,
    TemplateOutput,
)


class PostgresTemplate(InfraTemplate):
    """Standard postgres deployment. Creates an app DB plus a fusionauth DB
    if any other service in the project will need FusionAuth (the provisioner
    arranges this via a depends_on hint, not by inspection here).
    """

    DEFAULT_CONTAINER_PORT = 5432

    def render(self, ctx: TemplateContext) -> TemplateOutput:
        host_port = ctx.service.port or 5432
        # Emit the asyncpg-flavored URL because every shipped Python
        # skeleton (FastAPI) uses ``create_async_engine`` and would
        # otherwise fall back to psycopg2 — which we don't install.
        # A sync-Python skeleton can transform this URL at config-load.
        env_vars = {
            "POSTGRES_USER": "dev",
            "POSTGRES_PASSWORD": "dev",
            "POSTGRES_DB": ctx.project_slug,
            "DATABASE_URL": (
                f"postgresql+asyncpg://dev:dev@postgres:5432/{ctx.project_slug}"
            ),
        }

        # init.sql — create app DB + a fusionauth DB unconditionally so the
        # FusionAuth template can simply use it. Postgres' default entrypoint
        # auto-creates POSTGRES_DB; we add fusionauth via the docker-entrypoint
        # init dir.
        init_sql = (
            "-- Auto-generated by bizniz provisioner.\n"
            "-- Creates the FusionAuth database alongside the app database\n"
            "-- (the app database is created by the postgres entrypoint from\n"
            "-- POSTGRES_DB in .env).\n"
            "CREATE DATABASE fusionauth;\n"
            "GRANT ALL PRIVILEGES ON DATABASE fusionauth TO dev;\n"
        )

        compose_service = {
            "image": "postgres:16-alpine",
            "env_file": ".env",
            "ports": [f"{host_port}:5432"],
            "volumes": [
                "pgdata:/var/lib/postgresql/data",
                "./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro",
            ],
            "healthcheck": {
                "test": [
                    "CMD-SHELL",
                    "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB",
                ],
                "interval": "5s",
                "timeout": "3s",
                "retries": 5,
            },
            "networks": ["app-network"],
        }

        return TemplateOutput(
            compose_service=compose_service,
            compose_volumes=["pgdata"],
            compose_networks=["app-network"],
            infra_files={"postgres/init.sql": init_sql},
            env_vars=env_vars,
        )
