"""ProjectGit — per-project git ops baked into the v2 pipeline.

Roadmap item 3. Wraps git operations against
``<bizniz_projects>/<slug>/`` so each phase boundary produces a
durable revertible checkpoint:

  - Initial provision → commit + tag ``m0``
  - Each milestone DONE → commit + tag ``m<N>-done``
  - (Future) Each refactor extraction → commit + tag
    ``m<N>-refactor-<extractionId>`` (consumed by item 5)

Reverting (item 5's safety net):

  ``ProjectGit(project_root).revert_to_tag("m3-done")``

resets the entire project workspace + .bizniz state to that
checkpoint. Refactor agents that produce breaking changes can
roll back cleanly.

Robustness:

All ops are best-effort. If git isn't installed, the working tree
is in a weird state, or any subprocess fails, the methods log and
return False — they never raise out to the pipeline. A build
without git tracking is strictly no worse than the pre-item-3
world.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Callable, Optional


_DEFAULT_USER_NAME = "Bizniz Pipeline"
_DEFAULT_USER_EMAIL = "agent@bizniz.local"

# .gitignore content for generated project workspaces. Includes
# build artifacts + dev-only ephemerals + the .pytest_cache /
# node_modules churn that doesn't belong in history. Notably DOES
# track ``.bizniz/`` so reverts are coherent (the design_lock,
# project.db, ux caches all roll back together).
_DEFAULT_GITIGNORE = """\
# Generated by bizniz pipeline. Edit as needed; new entries will
# stick across milestones once committed.

# Node / frontend build outputs
node_modules/
dist/
build/
.next/
.vite/
.cache/
storybook-static/

# Python build outputs
__pycache__/
*.pyc
*.pyo
*.egg-info/
.pytest_cache/

# Per-developer environment (committed once via .env.example; the
# materialized .env contains keys/passwords specific to this run)
.env
.env.local

# OS / IDE
.DS_Store
.vscode/
.idea/

# Logs
*.log

# Postgres data volume (lives in named docker volume, but if it
# ever lands in the workspace we exclude it)
pgdata/

# Screenshot captures (per-run, not history)
screenshots/

# Storybook static build output (rebuilt per run)
storybook-static/
"""


class ProjectGit:
    """Best-effort git wrapper for a single generated project workspace."""

    def __init__(
        self,
        project_root: Path,
        on_status: Optional[Callable[[str], None]] = None,
        user_name: str = _DEFAULT_USER_NAME,
        user_email: str = _DEFAULT_USER_EMAIL,
    ):
        self._root = Path(project_root)
        self._on_status = on_status
        self._user_name = user_name
        self._user_email = user_email

    # ── Public ─────────────────────────────────────────────────────────

    def init_if_needed(self) -> bool:
        """Initialize a fresh git repo at the project root if one
        doesn't already exist. Configures local user.name + user.email
        so commits attribute cleanly. Writes a ``.gitignore`` template
        if missing. Returns True if init happened, False if already
        initialized OR if init failed."""
        if shutil.which("git") is None:
            self._log("ProjectGit: git binary not on PATH — skipping")
            return False
        if not self._root.is_dir():
            self._log(
                f"ProjectGit: project root {self._root} doesn't exist; "
                f"skipping init"
            )
            return False
        if (self._root / ".git").is_dir():
            # Already initialized. No-op.
            return False
        ok = self._run(["init", "-q"])
        if not ok:
            return False
        # Local config so commits don't fall back to global git config
        # (which may be set to the developer's identity).
        self._run(["config", "user.name", self._user_name])
        self._run(["config", "user.email", self._user_email])
        # Default branch — git's global default varies. Pin to main.
        self._run(["checkout", "-q", "-b", "main"])
        # Write .gitignore if not already present.
        gitignore = self._root / ".gitignore"
        if not gitignore.is_file():
            gitignore.write_text(_DEFAULT_GITIGNORE)
        self._log(
            f"ProjectGit: initialized fresh repo at {self._root} "
            f"(user.name={self._user_name})"
        )
        return True

    def commit_all(
        self,
        message: str,
        tag: Optional[str] = None,
        allow_empty: bool = False,
        body: Optional[str] = None,
    ) -> bool:
        """``git add -A`` then ``git commit -m <message>``; optionally
        create ``tag``. Returns True if a commit was made (and tag
        applied if requested), False on any failure or when there
        was nothing to commit (and ``allow_empty`` is False).

        ``body``, if provided, becomes a second ``-m`` argument and
        lands as the commit body. Callers pass a one-line
        ``[bizniz pipeline run <job_id>]`` so generated commits are
        grep-able without polluting the ``Co-Authored-By`` metadata
        field GitHub uses for contributor stats. Project commits do
        NOT carry ``Co-Authored-By: Claude`` by design — the
        generated project is the USER's product, not a bizniz/Claude
        contribution.

        Tag creation force-overwrites if the same tag already exists
        — supports re-running a phase + replacing its prior commit
        cleanly."""
        if not (self._root / ".git").is_dir():
            self._log(
                f"ProjectGit: no .git at {self._root}; skipping commit "
                f"({message!r})"
            )
            return False
        self._run(["add", "-A"])
        if not allow_empty and not self.is_dirty(staged_only=True):
            self._log(
                f"ProjectGit: nothing to commit for {message!r} — "
                f"skipping (workspace clean)"
            )
            # Still apply the tag if requested — useful when re-running
            # an already-committed phase + we want the tag pointer to
            # exist.
            if tag:
                self._run(["tag", "-f", tag])
            return False
        commit_args = ["commit", "-q", "-m", message]
        if body:
            commit_args.extend(["-m", body])
        if allow_empty:
            commit_args.append("--allow-empty")
        ok = self._run(commit_args)
        if not ok:
            return False
        if tag:
            self._run(["tag", "-f", tag])
        self._log(
            f"ProjectGit: committed {message!r}"
            + (f" (tag={tag})" if tag else "")
        )
        return True

    def is_dirty(self, staged_only: bool = False) -> bool:
        """``git status --porcelain`` non-empty → dirty.

        ``staged_only=True`` checks only staged changes (lines whose
        first column is not a space). Useful right after ``git add -A``
        to distinguish "added changes" from "nothing happened."
        """
        out = self._run_capture(["status", "--porcelain"])
        if out is None:
            return False
        if not out.strip():
            return False
        if not staged_only:
            return True
        # Staged-only: filter to lines where col[0] is a real status.
        for line in out.splitlines():
            if line[:1].strip():
                return True
        return False

    # ── v5 per-iter snapshots (2026-05-19) ─────────────────────────

    def snapshot_for_repair_iter(
        self,
        milestone_index: int,
        iter_idx: int,
    ) -> Optional[str]:
        """Commit current workspace state + tag it as the pre-state of
        ``milestone_index``'s repair iter ``iter_idx``. Returns the tag
        name on success, None on failure or no-op.

        Tag shape: ``m<milestone>-repair<iter>-pre``. Stable so v5's
        rollback can find it deterministically.

        v5 wires this before each repair iter so a regressing iter's
        changes can be rolled back via ``rollback_repair_iter``.
        """
        tag = f"m{milestone_index}-repair{iter_idx}-pre"
        # Commit only if the workspace has uncommitted changes; otherwise
        # the prior state is already the snapshot — just (re)apply the
        # tag pointing at HEAD.
        if self.is_dirty():
            ok = self.commit_all(
                message=f"v5 snapshot before m{milestone_index} repair iter {iter_idx}",
                tag=tag,
                allow_empty=True,
            )
            if not ok:
                # commit_all already logged; still try to apply the tag.
                if (self._root / ".git").is_dir():
                    self._run(["tag", "-f", tag])
            return tag
        if (self._root / ".git").is_dir():
            self._run(["tag", "-f", tag])
            self._log(
                f"ProjectGit: snapshot tag {tag} applied to HEAD "
                f"(workspace already clean)"
            )
            return tag
        return None

    def rollback_repair_iter(
        self,
        milestone_index: int,
        iter_idx: int,
    ) -> bool:
        """Reset the workspace to the snapshot tag for the start of
        ``milestone_index``'s repair iter ``iter_idx``. Destructive —
        discards any commits + working-tree changes since the snapshot.
        Returns True on success.

        v5 calls this when the resolution-check shows a regression:
        the repair iter is undone and the loop tries again with a
        different fix-issue scope.
        """
        tag = f"m{milestone_index}-repair{iter_idx}-pre"
        self._log(
            f"ProjectGit: rolling back to snapshot {tag} (regression "
            f"recovery)"
        )
        return self.revert_to_tag(tag)

    def revert_to_tag(self, tag: str) -> bool:
        """``git reset --hard <tag>`` — destructive but bounded. Used
        by the refactorer (roadmap item 5) when an extraction breaks
        tests and the safest move is to roll back to the last known-
        good checkpoint."""
        if not (self._root / ".git").is_dir():
            return False
        ok = self._run(["reset", "--hard", tag])
        if ok:
            self._log(
                f"ProjectGit: reverted workspace to tag {tag!r} "
                f"(destructive)"
            )
        return ok

    def current_head_sha(self) -> Optional[str]:
        """Return the current HEAD SHA, or None if unavailable."""
        out = self._run_capture(["rev-parse", "HEAD"])
        if out is None:
            return None
        return out.strip() or None

    # ── Internals ──────────────────────────────────────────────────────

    def _log(self, msg: str) -> None:
        if self._on_status:
            try:
                self._on_status(msg)
            except Exception:
                pass

    def _run(self, args: list) -> bool:
        """Run ``git <args>`` in the project root. Returns True on
        exit 0, False on any failure. Never raises."""
        try:
            proc = subprocess.run(
                ["git", *args],
                cwd=str(self._root),
                capture_output=True,
                text=True,
                timeout=60.0,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError) as e:
            self._log(
                f"ProjectGit: git {args[0]} raised {type(e).__name__}: {e}"
            )
            return False
        if proc.returncode != 0:
            self._log(
                f"ProjectGit: git {args[0]} exited {proc.returncode}: "
                f"{(proc.stderr or '').strip()[:200]}"
            )
            return False
        return True

    def _run_capture(self, args: list) -> Optional[str]:
        """Like ``_run`` but returns stdout on success, None on failure."""
        try:
            proc = subprocess.run(
                ["git", *args],
                cwd=str(self._root),
                capture_output=True,
                text=True,
                timeout=60.0,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError):
            return None
        if proc.returncode != 0:
            return None
        return proc.stdout
