"""AUTH_CONTRACT.md renderer.

Pure render: AuthManifest → markdown. The manifest reflects what
FusionAuth actually has, so the contract can NEVER claim a user or
role that doesn't exist in FA — that whole class of v1/v2 bug
(``AuthAgent: audit FAIL [test_users_in_fa]``) goes away by
construction.
"""
from __future__ import annotations

from bizniz.auth_operator.manifest import AuthManifest


def render_auth_contract(manifest: AuthManifest) -> str:
    """Render AUTH_CONTRACT.md from the post-apply manifest."""
    lines: list[str] = []
    lines.append("# Auth Contract")
    lines.append("")
    lines.append(
        "**Auto-generated by FusionAuthOperator. DO NOT EDIT** — "
        "regenerated each AuthAgent run from live FusionAuth state. "
        "Manual edits will be overwritten."
    )
    lines.append("")

    lines.append("## FusionAuth coordinates")
    lines.append("")
    lines.append(f"- Host URL: `{manifest.fa_url}`")
    lines.append(f"- Primary application ID: `{manifest.primary_app_id}`")
    lines.append(f"- Tenant ID: `{manifest.tenant_id}`")
    if manifest.issuer:
        lines.append(f"- Issuer (iss claim): `{manifest.issuer}`")
    lines.append("")

    lines.append("## JWT signing")
    lines.append("")
    sk = manifest.signing_key
    bound = []
    if sk.bound_to_app:
        bound.append("application")
    if sk.bound_to_tenant:
        bound.append("tenant")
    bound_str = " + ".join(bound) if bound else "(unbound)"
    lines.append(
        f"- Algorithm: **{sk.algorithm}** "
        f"({'RS-family ✓' if sk.is_rs_family else 'NOT RS-family ✗'})"
    )
    lines.append(f"- Key ID: `{sk.key_id or '(none)'}`")
    lines.append(f"- Bound to: {bound_str}")
    lines.append("")

    if manifest.applications:
        lines.append("## Applications")
        lines.append("")
        for app in manifest.applications:
            lines.append(
                f"- **{app.name}** (`{app.application_id}`) — "
                f"roles: {', '.join(app.role_names) or '(none)'}"
            )
        lines.append("")

    if manifest.roles:
        lines.append("## Roles")
        lines.append("")
        for role in manifest.roles:
            sup = " *[super_role]*" if role.is_super_role else ""
            desc = f" — {role.description}" if role.description else ""
            lines.append(f"- `{role.name}`{sup}{desc}")
        lines.append("")

    if manifest.users:
        lines.append("## Test users")
        lines.append("")
        lines.append(
            "Format: `email / password — roles role_name[, role_name]`. "
            "Used by integration tests; passwords are dev convention "
            "(production rotates on first login)."
        )
        lines.append("")
        for user in manifest.users:
            roles_str = ", ".join(user.roles) or "(none)"
            verified = " ✓" if user.login_verified else " ✗ login unverified"
            lines.append(
                f"- {user.email} / {user.password} — roles {roles_str}"
                f"{verified}"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
